In [1]:
import numpy as np
import toric
import ldpc.code_util

# Toric Code
This is the usual toric code on a torus, so there are 2 logical qubits. We use a distance of `d`.

## Codes

In [2]:
d = 5
H = toric.toric_code_x(d)

In [3]:
H.toarray()

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 1, 1]], shape=(25, 50), dtype=uint8)

We use utilities from Jaoschka Roffe's `ldpc` library to compute code parameters. Note that this code only works for classical parity check matrices. So it has no knowledge of quantum structure. If we run it on a quantum code, it'll treat it like a classical code on bits.

In [4]:
ldpc.code_util.compute_code_parameters(H)

(50, 26, 4)

What? Why are there $d^2 + 1$ logical qubits??? We have only used the X checks. There are d^2 of them, but one is not linearly independent (the product of all d^2 is the identity). The distance appears to be $\mathrm{min}(4, d)$. Why? Because both the Z logicals and the Z stabilizers are technically logical operators.

In [5]:
H = toric.toric_code_z(d)

In [6]:
ldpc.code_util.compute_code_parameters(H)

(50, 26, 4)

The $Z$ code has the same properties as the $X$ code. Again, $X$ stabilizers and logicals are the logical operators of this classical code.

In [7]:
H = toric.toric_code(d, verbose=False)

In [8]:
H.shape

(50, 100)

In [9]:
ldpc.code_util.compute_code_parameters(H)

(100, 52, 4)

In [10]:
np.allclose((H @ toric.symplectic(2*d**2) @ H.T).data % 2, 0)

True

## Logical operators

In [11]:
log, ip = toric.toric_code_logical(d, verbose=True)

Generate X logicals
[1, 11, 21, 31, 41]
[0, 2, 4, 6, 8]
Generate Z logicals
[0, 10, 20, 30, 40]
[1, 3, 5, 7, 9]


In [13]:
ip.toarray()

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]], dtype=uint8)

In [12]:
ldpc.code_util.compute_code_parameters(log)

(100, 96, 1)

The distance is one; there are some single qubit operators that commute with all logical operators.

# Surface code

# Codes

In [14]:
d = 5
k = 5

In [15]:
H = toric.surface_code_x(d, k, verbose=False)

In [16]:
ldpc.code_util.compute_code_parameters(H)

(187, 97, 3)

In [17]:
H = toric.surface_code_z(d, k, verbose=False)

In [18]:
ldpc.code_util.compute_code_parameters(H)

(187, 95, 3)

In [19]:
H = toric.surface_code(d, k, verbose=False)
print(H.shape)

(182, 374)


In [20]:
ldpc.code_util.compute_code_parameters(H)

(374, 192, 3)

Now the distance is 3 since there are 3 body operators.

## Logicals

In [28]:
log, ip = toric.surface_code_logical(d, k, verbose=True)

Lx=18, Ly=5
boundary_x=[False False]
boundary_y=[ True  True  True False False False False False  True  True False False
 False False False  True  True  True]
num_qubits=187
Generate X logicals
[182, 183, 184, 185, 186]
[37, 48, 59, 70, 81]
[27, 38, 49, 60, 71]
[110, 121, 132, 143, 154]
[100, 111, 122, 133, 144]
Lx=18, Ly=5
boundary_x=[False False]
boundary_y=[ True  True  True False False False False False  True  True False False
 False False False  True  True  True]
num_qubits=187
Generate Z logicals
[8, 17, 26, 36, 37]
[0, 9, 18, 28, 27]
[81, 90, 99, 109, 110]
[71, 82, 91, 101, 100]
[144, 155, 164, 173, 182]


In [29]:
ip.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=uint8)

`ip` indicates which Paulis anticommute with one another. We are choosing an irregular basis of the $k$ logical qubits. Rather than choosing $X_i$ and $Z_i$, we instead use products $\prod Z_i$ and $\prod X_i$ such that operators are horizontal (in the time direction for contraction).

In [30]:
ldpc.code_util.compute_code_parameters(log)

(374, 364, 1)